version: "3.9"

services:
  # --- INFRASTRUCTURE ---
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - notification-net

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - notification-net

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - notification-net

  # --- MICROSERVICES ---
  
  api-gateway:
    build: ./api-gateway 
    container_name: api-gateway
    ports:
      - "8000:8000"
    command:
      uvicorn app.main:app --host 0.0.0.0 --port 8000 
    networks:
      - notification-net
    environment:
    - SERVICE_NAME=api-gateway
    - ENVIRONMENT=development
    - DEBUG=True
    - SERVICE_PORT=8000

    - RABBITMQ_HOST=rabbitmq
    - RABBITMQ_PORT=5672
    - RABBITMQ_USER=guest
    - RABBITMQ_PASS=guest
    - RABBITMQ_VHOST=/
    - RABBITMQ_EXCHANGE=notifications
    - RABBITMQ_EXCHANGE_TYPE=topic

    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - REDIS_DB=0
    - REDIS_DECODE_RESPONSES=True

    - JWT_SECRET=${JWT_SECRET}
    - JWT_ALGORITHM=HS256
    - JWT_EXPIRATION=3600

    - RATE_LIMIT_REQUESTS=100
    - RATE_LIMIT_WINDOW=60
    - NOTIFICATION_STATUS_TTL=3600
    - IDEMPOTENCY_TTL=3600

    - USER_SERVICE_URL=http://user-service:3001

    depends_on:
      - rabbitmq
      - redis
      - user-service

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001" 
    networks:
      - notification-net
    environment:
      - SERVICE_PORT=3001
      - DB_HOST=postgres
      - DB_USERNAME=admin
      - DB_PASSWORD=password
      - DB_DATABASE=user_db
      - JWT_SECRET=${JWT_SECRET}

    # volumes:
    #   - ./user-service:/usr/src/app

    depends_on:
      - postgres

  template-service:
    build: ./template-service
    container_name: template-service
    ports:
      - "8085:8085"
    networks:
      - notification-net
    environment:
      - SERVICE_PORT=8085
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/template_db
      - SPRING_DATASOURCE_PASSWORD=password

    volumes:
      - ./template-service/src:/app/src
    depends_on:
      - postgres

  push-service:
    build: ./push-service
    container_name: push-service
    networks:
      - notification-net
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_REDIS_HOST=redis
      - USER_SERVICE_URL=http://user-service:3001
      - TEMPLATE_SERVICE_URL=http://template-service:8085
      - STATUS_UPDATE_URL=http://api-gateway:8000/api/v1/push/status/

    volumes:
      - ./push-service/src:/app/src

    depends_on:
      - rabbitmq
      - redis
      - user-service
      - template-service

  email-service:
    build: ./email-service
    container_name: email-service
    networks:
      - notification-net
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379
      - USER_SERVICE_URL=http://user-service:3001
      - TEMPLATE_SERVICE_URL=http://template-service:8085
      - STATUS_UPDATE_URL=http://api-gateway:8000/api/v1/email/status/
    depends_on:
      - rabbitmq
      - redis
      - user-service
      - template-service

networks:
  notification-net:
    driver: bridge

volumes:
  rabbitmq_data:
  redis_data:
  postgres_data: